//
//  HPSConvolutionIRsInt.h
//  Convolution Reverb IRs
//
//  Created by Richard Zhang on 7/20/17.
//  Copyright (c) 2016 Hear360 All rights reserved.
//

#ifndef BinarualLib_HPSConvolutionIRs_h
#define BinarualLib_HPSConvolutionIRs_h

#define HPS_CONVOLUTION_IR_DEFAULT_SET
// #define HPS_CONVOLUTION_IR_SOUNDFI_SET
// #define HPS_CONVOLUTION_IR_SOUNDFI2_SET
// #define HPS_CONVOLUTION_IR_SOUNDFI3_SET
// #define HPS_CONVOLUTION_IR_HYBRIDC_SET

#define HPS_CONVOLUTION_IR_DEFAULT_SKY_SET
// #define HPS_CONVOLUTION_IR_SOUNDFI_SKY_SET
// #define HPS_CONVOLUTION_IR_SOUNDFI2_SKY_SET
// #define HPS_CONVOLUTION_IR_SOUNDFI3_SKY_SET
// #define HPS_CONVOLUTION_IR_HYBRIDC_SKY_SET

//#define HPS_CONVOLUTION_LEGACY_GAIN
//#define HPS_CONVOLUTION_IR_FORCE_44_1_KHZ
//#define HPS_CONVOLUTION_IR_ADDITION_5_CHANNELS
//#define HPS_CONVOLUTION_IR_LFE_PROCESS

#endif
